CI syntax fix

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -37,4 +37,4 @@ jobs:
         run: ansible-playbook -i tests/inventory tests/test.yml
 
       - name: Rerun Ansible for idempotence check (allow less changes)
-        run: "ansible-playbook -i tests/inventory tests/test.yml" | grep -q 'changed=2.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+        run: "ansible-playbook -i tests/inventory tests/test.yml | grep -q 'changed=2.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
